server:
  port: 8080
  debug: true

mysql:
  host: localhost
  port: 3306
  database: test
  username: root
  password: 12345678

minio:
  endpoint: localhost:9000
#  accessKeyID: w89rqJsFURucLp0nKKj8
#  secretAccessKey: E3s0BfoZ3bhA0u3CZ1FERTvz7zgQWVznH5T3FhsY
  accessKeyID: va86bRfan1I1NZxHWx6W
  secretAccessKey: AZvVBUlj0nMonidgF70pRU06zoop4ZMEsxJSfKRE
  bucketName: simple-blog